version: '3.8'

services:
  mysql:
    container_name: mysql-container
    image: mysql:5.7
    command: [--ignore-db-dir=lost+found]
    restart: always
    environment:
      - MYSQL_DB=${TYPEORM_DATABASE}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_ROOT_PASSWORD}
      - MYSQL_USER=${TYPEORM_USERNAME}
      - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysqil/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    expose:
      - '${TYPEORM_PORT}'
  backend:
    container_name: nest-example
    build:
      context: .
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - '${API_PORT}:${API_PORT}'
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=${TYPEORM_HOST}